/** @typedef {object} json
 * @property {number} id
 * @property {string} date
 * @property {string} date_gmt
 * @property {object} guid
 * @property {string} guid.rendered
 * @property {string} modified
 * @property {string} modified_gmt
 * @property {string} slug
 * @property {string} status
 * @property {string} type
 * @property {string} link
 * @property {object} title
 * @property {string} title.rendered
 * @property {object} content
 * @property {string} content.rendered
 * @property {boolean} content.protected
 * @property {object} excerpt
 * @property {string} excerpt.rendered
 * @property {boolean} excerpt.protected
 * @property {number} author
 * @property {number} featured_media
 * @property {string} comment_status
 * @property {string} ping_status
 * @property {boolean} sticky
 * @property {string} template
 * @property {string} format
 * @property {object} meta
 * @property {string} meta.footnotes
 * @property {number[]} categories
 * @property {number[]} tags
 * @property {string[]} class_list
 * @property {string} yoast_head
 * @property {object} yoast_head_json
 * @property {string} yoast_head_json.title
 * @property {object} yoast_head_json.robots
 * @property {string} yoast_head_json.robots.index
 * @property {string} yoast_head_json.robots.follow
 * @property {string} yoast_head_json.robots.max-snippet
 * @property {string} yoast_head_json.robots.max-image-preview
 * @property {string} yoast_head_json.robots.max-video-preview
 * @property {string} yoast_head_json.og_locale
 * @property {string} yoast_head_json.og_type
 * @property {string} yoast_head_json.og_title
 * @property {string} yoast_head_json.og_description
 * @property {string} yoast_head_json.og_url
 * @property {string} yoast_head_json.og_site_name
 * @property {string} yoast_head_json.article_published_time
 * @property {string} yoast_head_json.article_modified_time
 * @property {object[]} yoast_head_json.og_image
 * @property {string} yoast_head_json.og_image.url
 * @property {string} yoast_head_json.og_image.type
 * @property {string} yoast_head_json.og_image.width
 * @property {string} yoast_head_json.og_image.height
 * @property {string} yoast_head_json.author
 * @property {string} yoast_head_json.twitter_card
 * @property {object} yoast_head_json.twitter_misc
 * @property {string} yoast_head_json.twitter_misc.Scritto da
 * @property {string} yoast_head_json.twitter_misc.Tempo di lettura stimato
 * @property {object} yoast_head_json.schema
 * @property {string} yoast_head_json.schema.@context
 * @property {object[]} yoast_head_json.schema.@graph
 * @property {string} yoast_head_json.schema.@graph.@type
 * @property {string} yoast_head_json.schema.@graph.@id
 * @property {string} yoast_head_json.schema.@graph.url
 * @property {string} yoast_head_json.schema.@graph.name
 * @property {object} yoast_head_json.schema.@graph.isPartOf
 * @property {string} yoast_head_json.schema.@graph.isPartOf.@id
 * @property {object} yoast_head_json.schema.@graph.primaryImageOfPage
 * @property {string} yoast_head_json.schema.@graph.primaryImageOfPage.@id
 * @property {object} yoast_head_json.schema.@graph.image
 * @property {string} yoast_head_json.schema.@graph.image.@id
 * @property {string} yoast_head_json.schema.@graph.thumbnailUrl
 * @property {string} yoast_head_json.schema.@graph.datePublished
 * @property {string} yoast_head_json.schema.@graph.dateModified
 * @property {object} yoast_head_json.schema.@graph.author
 * @property {string} yoast_head_json.schema.@graph.author.@id
 * @property {object} yoast_head_json.schema.@graph.breadcrumb
 * @property {string} yoast_head_json.schema.@graph.breadcrumb.@id
 * @property {string} yoast_head_json.schema.@graph.inLanguage
 * @property {object[]} yoast_head_json.schema.@graph.potentialAction
 * @property {string} yoast_head_json.schema.@graph.potentialAction.@type
 * @property {string[]|object} yoast_head_json.schema.@graph.potentialAction.target
 * @property {string} yoast_head_json.schema.@graph.contentUrl
 * @property {number} yoast_head_json.schema.@graph.width
 * @property {number} yoast_head_json.schema.@graph.height
 * @property {object[]} yoast_head_json.schema.@graph.itemListElement
 * @property {string} yoast_head_json.schema.@graph.itemListElement.@type
 * @property {number} yoast_head_json.schema.@graph.itemListElement.position
 * @property {string} yoast_head_json.schema.@graph.itemListElement.name
 * @property {string} yoast_head_json.schema.@graph.itemListElement.item
 * @property {string} yoast_head_json.schema.@graph.description
 * @property {string} yoast_head_json.schema.@graph.potentialAction.target.@type
 * @property {string} yoast_head_json.schema.@graph.potentialAction.target.urlTemplate
 * @property {object} yoast_head_json.schema.@graph.potentialAction.query-input
 * @property {string} yoast_head_json.schema.@graph.potentialAction.query-input.@type
 * @property {boolean} yoast_head_json.schema.@graph.potentialAction.query-input.valueRequired
 * @property {string} yoast_head_json.schema.@graph.potentialAction.query-input.valueName
 * @property {string} yoast_head_json.schema.@graph.image.@type
 * @property {string} yoast_head_json.schema.@graph.image.inLanguage
 * @property {string} yoast_head_json.schema.@graph.image.url
 * @property {string} yoast_head_json.schema.@graph.image.contentUrl
 * @property {string} yoast_head_json.schema.@graph.image.caption
 * @property {string[]} yoast_head_json.schema.@graph.sameAs
 * @property {object} _links
 * @property {object[]} _links.self
 * @property {string} _links.self.href
 * @property {object} _links.self.targetHints
 * @property {string[]} _links.self.targetHints.allow
 * @property {object[]} _links.collection
 * @property {string} _links.collection.href
 * @property {object[]} _links.about
 * @property {string} _links.about.href
 * @property {object[]} _links.author
 * @property {boolean} _links.author.embeddable
 * @property {string} _links.author.href
 * @property {object[]} _links.replies
 * @property {boolean} _links.replies.embeddable
 * @property {string} _links.replies.href
 * @property {object[]} _links.version-history
 * @property {number} _links.version-history.count
 * @property {string} _links.version-history.href
 * @property {object[]} _links.predecessor-version
 * @property {number} _links.predecessor-version.id
 * @property {string} _links.predecessor-version.href
 * @property {object[]} _links.wp:attachment
 * @property {string} _links.wp:attachment.href
 * @property {object[]} _links.wp:term
 * @property {string} _links.wp:term.taxonomy
 * @property {boolean} _links.wp:term.embeddable
 * @property {string} _links.wp:term.href
 * @property {object[]} _links.curies
 * @property {string} _links.curies.name
 * @property {string} _links.curies.href
 * @property {boolean} _links.curies.templated
 * @property {object} _embedded
 * @property {object[]} _embedded.author
 * @property {number} _embedded.author.id
 * @property {string} _embedded.author.name
 * @property {string} _embedded.author.url
 * @property {string} _embedded.author.description
 * @property {string} _embedded.author.link
 * @property {string} _embedded.author.slug
 * @property {object} _embedded.author.avatar_urls
 * @property {string} _embedded.author.avatar_urls.24
 * @property {string} _embedded.author.avatar_urls.48
 * @property {string} _embedded.author.avatar_urls.96
 * @property {object} _embedded.author.bookmarked_posts
 * @property {number} _embedded.author.bookmarked_posts.5
 * @property {number} _embedded.author.bookmarked_posts.6
 * @property {number} _embedded.author.bookmarked_posts.7
 * @property {number} _embedded.author.bookmarked_posts.11
 * @property {number} _embedded.author.bookmarked_posts.19
 * @property {number} _embedded.author.bookmarked_posts.21
 * @property {number} _embedded.author.bookmarked_posts.22
 * @property {number} _embedded.author.bookmarked_posts.23
 * @property {string} _embedded.author.yoast_head
 * @property {object} _embedded.author.yoast_head_json
 * @property {string} _embedded.author.yoast_head_json.title
 * @property {object} _embedded.author.yoast_head_json.robots
 * @property {string} _embedded.author.yoast_head_json.robots.index
 * @property {string} _embedded.author.yoast_head_json.robots.follow
 * @property {string} _embedded.author.yoast_head_json.robots.max-snippet
 * @property {string} _embedded.author.yoast_head_json.robots.max-image-preview
 * @property {string} _embedded.author.yoast_head_json.robots.max-video-preview
 * @property {string} _embedded.author.yoast_head_json.og_locale
 * @property {string} _embedded.author.yoast_head_json.og_type
 * @property {string} _embedded.author.yoast_head_json.og_title
 * @property {string} _embedded.author.yoast_head_json.og_url
 * @property {string} _embedded.author.yoast_head_json.og_site_name
 * @property {object[]} _embedded.author.yoast_head_json.og_image
 * @property {string} _embedded.author.yoast_head_json.og_image.url
 * @property {string} _embedded.author.yoast_head_json.og_image.type
 * @property {string} _embedded.author.yoast_head_json.og_image.width
 * @property {string} _embedded.author.yoast_head_json.og_image.height
 * @property {string} _embedded.author.yoast_head_json.twitter_card
 * @property {object} _embedded.author.yoast_head_json.schema
 * @property {string} _embedded.author.yoast_head_json.schema.@context
 * @property {object[]} _embedded.author.yoast_head_json.schema.@graph
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.@type
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.@id
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.url
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.name
 * @property {object} _embedded.author.yoast_head_json.schema.@graph.isPartOf
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.isPartOf.@id
 * @property {object} _embedded.author.yoast_head_json.schema.@graph.breadcrumb
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.breadcrumb.@id
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.inLanguage
 * @property {object[]} _embedded.author.yoast_head_json.schema.@graph.potentialAction
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.potentialAction.@type
 * @property {string[]|object} _embedded.author.yoast_head_json.schema.@graph.potentialAction.target
 * @property {object[]} _embedded.author.yoast_head_json.schema.@graph.itemListElement
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.itemListElement.@type
 * @property {number} _embedded.author.yoast_head_json.schema.@graph.itemListElement.position
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.itemListElement.name
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.itemListElement.item
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.description
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.potentialAction.target.@type
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.potentialAction.target.urlTemplate
 * @property {object} _embedded.author.yoast_head_json.schema.@graph.potentialAction.query-input
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.potentialAction.query-input.@type
 * @property {boolean} _embedded.author.yoast_head_json.schema.@graph.potentialAction.query-input.valueRequired
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.potentialAction.query-input.valueName
 * @property {object} _embedded.author.yoast_head_json.schema.@graph.image
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.@type
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.inLanguage
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.@id
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.url
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.contentUrl
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.image.caption
 * @property {string[]} _embedded.author.yoast_head_json.schema.@graph.sameAs
 * @property {object} _embedded.author.yoast_head_json.schema.@graph.mainEntityOfPage
 * @property {string} _embedded.author.yoast_head_json.schema.@graph.mainEntityOfPage.@id
 * @property {object} _embedded.author._links
 * @property {object[]} _embedded.author._links.self
 * @property {string} _embedded.author._links.self.href
 * @property {object} _embedded.author._links.self.targetHints
 * @property {string[]} _embedded.author._links.self.targetHints.allow
 * @property {object[]} _embedded.author._links.collection
 * @property {string} _embedded.author._links.collection.href
 * @property {array[]|object[]} _embedded.wp:term
 * @property {number} _embedded.wp:term.id
 * @property {string} _embedded.wp:term.link
 * @property {string} _embedded.wp:term.name
 * @property {string} _embedded.wp:term.slug
 * @property {string} _embedded.wp:term.taxonomy
 * @property {string} _embedded.wp:term.yoast_head
 * @property {object} _embedded.wp:term.yoast_head_json
 * @property {string} _embedded.wp:term.yoast_head_json.title
 * @property {object} _embedded.wp:term.yoast_head_json.robots
 * @property {string} _embedded.wp:term.yoast_head_json.robots.index
 * @property {string} _embedded.wp:term.yoast_head_json.robots.follow
 * @property {string} _embedded.wp:term.yoast_head_json.robots.max-snippet
 * @property {string} _embedded.wp:term.yoast_head_json.robots.max-image-preview
 * @property {string} _embedded.wp:term.yoast_head_json.robots.max-video-preview
 * @property {string} _embedded.wp:term.yoast_head_json.og_locale
 * @property {string} _embedded.wp:term.yoast_head_json.og_type
 * @property {string} _embedded.wp:term.yoast_head_json.og_title
 * @property {string} _embedded.wp:term.yoast_head_json.og_description
 * @property {string} _embedded.wp:term.yoast_head_json.og_url
 * @property {string} _embedded.wp:term.yoast_head_json.og_site_name
 * @property {string} _embedded.wp:term.yoast_head_json.twitter_card
 * @property {object} _embedded.wp:term.yoast_head_json.schema
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@context
 * @property {object[]} _embedded.wp:term.yoast_head_json.schema.@graph
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.@type
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.@id
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.url
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.name
 * @property {object} _embedded.wp:term.yoast_head_json.schema.@graph.isPartOf
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.isPartOf.@id
 * @property {object} _embedded.wp:term.yoast_head_json.schema.@graph.breadcrumb
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.breadcrumb.@id
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.inLanguage
 * @property {object[]} _embedded.wp:term.yoast_head_json.schema.@graph.itemListElement
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.itemListElement.@type
 * @property {number} _embedded.wp:term.yoast_head_json.schema.@graph.itemListElement.position
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.itemListElement.name
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.itemListElement.item
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.description
 * @property {object[]} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.@type
 * @property {object} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.target
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.target.@type
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.target.urlTemplate
 * @property {object} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.query-input
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.query-input.@type
 * @property {boolean} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.query-input.valueRequired
 * @property {string} _embedded.wp:term.yoast_head_json.schema.@graph.potentialAction.query-input.valueName
 * @property {object} _embedded.wp:term._links
 * @property {object[]} _embedded.wp:term._links.self
 * @property {string} _embedded.wp:term._links.self.href
 * @property {object} _embedded.wp:term._links.self.targetHints
 * @property {string[]} _embedded.wp:term._links.self.targetHints.allow
 * @property {object[]} _embedded.wp:term._links.collection
 * @property {string} _embedded.wp:term._links.collection.href
 * @property {object[]} _embedded.wp:term._links.about
 * @property {string} _embedded.wp:term._links.about.href
 * @property {object[]} _embedded.wp:term._links.wp:post_type
 * @property {string} _embedded.wp:term._links.wp:post_type.href
 * @property {object[]} _embedded.wp:term._links.curies
 * @property {string} _embedded.wp:term._links.curies.name
 * @property {string} _embedded.wp:term._links.curies.href
 * @property {boolean} _embedded.wp:term._links.curies.templated
 */
